# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-28 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(max_length=50)),
                ('from_address', models.TextField(blank=True, null=True)),
                ('from_contact', models.IntegerField()),
                ('to_name', models.CharField(max_length=50)),
                ('to_address', models.TextField(blank=True, null=True)),
                ('to_contact', models.IntegerField()),
                ('to_email', models.EmailField(max_length=254)),
                ('parcel_weight', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courier_Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('place', models.CharField(max_length=25)),
                ('remarks', models.TextField()),
                ('courier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Courier_Details')),
            ],
        ),
    ]
