# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-28 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200328_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier_tracking',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Dispatched', 'Dispatched'), ('Deplayed', 'Deplayed'), ('Wrong Address', 'Wrong Address'), ('No one', 'No one')], default=1, max_length=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courier_details',
            name='to_address',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courier_tracking',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
