# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-30 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20200328_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier_details',
            name='date_booked',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
